# Generated by Django 5.0.2 on 2024-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mymodel_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
